### ISSUE TITLE
Include htmengine instantiation to enrich streaming data

### ISSUE THREAD

**Issue by passiweinberger** [nupic-community/river-view#109]
THIS WILL BE AWESOME!

So the idea is to have river-view itself instantiate a new htmengine model for each new (and in the beginning exisiting) river, and automatically include the htmengine functionality to enrich each datastream in here with the anomalyScore. 

this will have the huge advantage that one no longer needs to write his/her own client for pushing and instantiating the models, but will have already trained ones and the past anomaly scores availible in here. 

Thoughts?
I know this is a huge serverload and we'd need a seperate htmengine server to hold the models for river-view, but i feel like this is a ultimate must-be feature for this.

**Comment by rhyolight** [comment]
I like your idea Pascal, but I think it is outside the scope of what River View should do. I want to keep this a simple project that caches and serves data. 

That being said, there is no reason another project entirely could be created in a way that interfaces with a River View instance and does exactly what you are saying. It could even show a web UI that graphs input data and predictions.
