### ISSUE TITLE
Update all SODA rivers to use the new API format

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#125]
Example of the new Tree Debris: http://dev.socrata.com/foundry/#/data.cityofchicago.org/ee5t-jv3t

And some other docs I was pointed to by @chrismetcalf on IRC:
- http://dev.socrata.com/docs/datatypes/point.html

**Comment by chrismetcalf** [comment]
Yay!

**Comment by rhyolight** [comment]
Already done!
