### ISSUE TITLE
Update the river config spec for non-continuous data  

### ISSUE THREAD

**Issue by jaredweiss** [nupic-community/river-view#30]
i.e. stock market data that should only make requests during the period the market is open 

Should be helpful for getting #4 up and running

**Comment by rhyolight** [comment]
I thought about defining river polling with a crontab instead of just an
interval.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jaredweiss** [comment]
Are there major advantages to doing that other than just having the front end and backend in separate processes? I think it's very convenient to be able to specify the interval within the `config.yml`. If the frontend/backend separation is the main concern could the data collector and the web server just be separate node programs?

**Comment by rhyolight** [comment]
I don't really care about the separation between the data-server and the
frontend. But it might be useful to be able to specify river polling with
more than just an interval. Ideally, I would like to specify something like
"weekdays between 9am - 5PM at 10 minute intervals". I don't think you can
do this with crontab but I'm not sure.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta
