### ISSUE TITLE
Help with nostradamIQ streams?

### ISSUE THREAD

**Issue by passiweinberger** [nupic-community/river-view#36]
Any of these: 
https://github.com/nupic-community/nostradamIQ/blob/master/datasets.md

or these:

https://docs.google.com/spreadsheets/d/1BaUdfMQtHB4eHj4pG7NHBVyCe_dbGHkNdZ8aupXvFXo/edit?usp=docslist_api

would be an awesome help!!!

**Comment by rhyolight** [comment]
http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php looks promising...

**Comment by passiweinberger** [comment]
yeah, although i currently try to get a river for https://twitter.com/USGSted as they as way faster ;)

**Comment by passiweinberger** [comment]
http://ghin.pdc.org/ghin/catalog/search/browse/browse.page here are some as well :)

**Comment by rhyolight** [comment]
> yeah, although i currently try to get a river for https://twitter.com/USGSted as they as way faster ;)

Take a look at https://github.com/nupic-community/river-view/tree/master/rivers/twitter-511nyc. It monitors a very similar twitter feed. Because some tweets have a link to more data, the 511nyc river actually opens the URL and scrapes the page for even more data.

**Comment by passiweinberger** [comment]
Guess what I was doing?  :D
As I'm at the CNS in prague i don't really make progress this week; I'll
come back to you after that :)
In the meanwhile; Thanks for the tests and consider spreading the word
about the datasets for nostradamIQ, maybe someone wants to help ;)

**Comment by rhyolight** [comment]
Hopefully we are helping with earthquake stuff. Sorry for misleading you about the twitter stream in #51.

**Comment by passiweinberger** [comment]
No Prob! 

Thank you!! Well this is more of a marathon, so please maybe keep hinting people to intigrate one of these https://github.com/nupic-community/nostradamIQ/blob/master/datasets.md :)
