### ISSUE TITLE
Yahoo! Stocks

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#4]
https://greenido.wordpress.com/2009/12/22/yahoo-finance-hidden-api/

**Comment by jaredweiss** [comment]
Yahoo's YQL might be a better option for this. It has a REST api that returns results as either XML or JSON which would be easier to parse than a csv file. 

You can interact w/ it here and try out different queries: https://developer.yahoo.com/yql/console/

Documentation: https://developer.yahoo.com/yql/

**Comment by jaredweiss** [comment]
@rhyolight 
Can this be closed?

**Comment by rhyolight** [comment]
Yes

**Comment by jaredweiss** [comment]
Closed by #50 and #92
