### ISSUE TITLE
Create automated river tests

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#5]
I want a test suite that will run against all rivers and validate that:

- They have the correct files in place
- The config contains the right info
- The parser can be sent the response from the URL(s) in the config and returns the properly formatted data to the callbacks.

This will allow people to create new rivers without having to run Redis locally.

**Comment by jaredweiss** [comment]
Does your third bullet point mean that the fields and metadata will have to directly map (in name) to the responses from the URLs or does this suggest additional info in the config defining what the response should look like from each of the URLs?

**Comment by rhyolight** [comment]
I think all we can do is check that the data sent to the first callback for temporal data has the same length as the `fields` in the config. Some of the items in the list might be null, that is okay, but the length must be the same. 

For the metadata callback, I think we just need to ensure it's not null. Otherwise the data could have any structure, as long as it is able to be `JSON.stringify`-ed.
