### ISSUE TITLE
Convert existing twitter earthquakes feed to use stable USGS JSON feed

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#51]
@passiweinberger I really do appreciate that you've created a river and are trying to get it working properly, but I have some concerns with the `twitter_earthquakes` river. 

HTML scraping is risky and brittle. It should only be used as a last resort. It Twitter decides to change how they use HTML classes on their website, it would easily break all twitter-based rivers. I created the twitter-511nyc river in a desparate attempt to get some live feed of traffic incidents to go along with the HTM Engine Tutorial, but honestly it has not worked out very well and I'm thinking of removing it entirely because the data quality is so bad. What you **really** want is the data source of the twitter feed if you can find it. 

In my case with the 511 data, I could not find that data source, but for USGS earthquake data, I have found several live-updated JSON feeds that probably give you much more info much more easily. 

http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php

I suggest you remove your twitter_earthquakes feed and replace it with an hourly feed (that updates every 5 minutes): http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson. 

This will be much stabler and easier to maintain, and the data is a much higher quality.

**Comment by jefffohl** [comment]
You guys are aware that Twitter offers a streaming API, correct? Wouldn't this be what you are looking for? https://dev.twitter.com/streaming/reference/post/statuses/filter

**Comment by rhyolight** [comment]
Is the Twitter streaming API available without an API key or authentication?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
No. You need to register an app with Twitter in order to get the data. Though, it is free. So, anyone setting up River View that uses Twitter feeds would need to register with Twitter and get the appropriate credentials. This means that we would need to set up an option for enabling/disabling individual streams instead of turning them all on by default.

**Comment by jefffohl** [comment]
I'm actually not sure if you would need to register with Twitter for each running instance of River View. One might be sufficient. I can take a look into it if there is interest.

**Comment by rhyolight** [comment]
River View was designed under the assumption that all rivers could be populated without any authentication whatsoever. I don't want to change this at this point. If there is enough pressure to add some type of authenticated feeds, I'm willing to discuss it in a separate issue.

**Comment by jefffohl** [comment]
Seems like we could make a "twitter-view" app that extends river-view, but instead is focused specifically on Twitter feeds. Users could specify any number of Twitter streams within the app, and turn them on and off.

**Comment by passiweinberger** [comment]
@rhyolight Thank you! I appreciate this, and have been looking into it before... THe main point of using twitter here was that USGSTed tweets about 'Preliminary' alerts. Hence its about 10mins faster then their geojson service. 10 mins in the situation of instant eqs alerts (which is one of the features to be in nostradamIQ) are a lifetime. 
Maybe we could have both? one for instant alerts and one for stable alerts? 
I like @jefffohl s Idea about querying the twitter api.. 
We could set up a twitter account for river-view and using its OAuth keys? 
Two separate rivers would be somewhat more annoying..

**Comment by rhyolight** [comment]
I think what I would like to do initially is replace the twitter quake feed with the JSON feed, then we can talk about how to get more up-to-date data.

**Comment by passiweinberger** [comment]
:+1:
