### ISSUE TITLE
Financial data rivers (stock, forex, ..) 

### ISSUE THREAD

**Issue by breznak** [nupic-community/river-view#84]
add other financial data sources
- [ ] [Yahoo Finance river](https://github.com/nupic-community/river-view/issues/4)
- [ ] Fundamental analysis data (eg. Morning star: 600 factors, available from https://github.com/quantopian/zipline , not sure about licence issues)
- [ ] Cooperate with pandas  to separate datasources into a separate project (@rhyolight what do you think about https://github.com/pydata/pandas/issues/8961 ? )

**Comment by rhyolight** [comment]
I definitely want to see the stocks. @jaredweiss has been working on it in https://github.com/nupic-community/river-view/pull/50, and I think it will be merged soon. 

I don't think of River View as a data analysis tool, but simply a data provider. I think all analysis should be done by consumers of Rivers. So I don't agree with your 2nd bullet. 

And for pandas... I'd be happy to try to make River data more easy to use by pandas, but I'm not sure what we could do help with https://github.com/pydata/pandas/issues/8961. 

Also, keep in mind this is entirely a Node.js program, so we cannot import python modules.

**Comment by breznak** [comment]
> Also, keep in mind this is entirely a Node.js program, so we cannot import python modules.

oh, my bad :/ 

> I don't think of River View as a data analysis tool, but simply a data provider. I think all analysis should be done by consumers of Rivers. So I don't agree with your 2nd bullet. 

I think this would be a useful source, it's not a raw data per-say, but can be seen as a data pool imho. For each tick you get (precomputed by the analytical methods) a vector of 600 values. This could be interesting data to crunch. 

@rhyolight this was just a suggestion, please feel free to close as you see fit.
