### ISSUE TITLE
Create JavaScript HTTP client for River View on NPM

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/river-view#89]
This should be in a new repo called `river-view-client-js`.

It should install with `npm install river-view-client`.

**Comment by jefffohl** [comment]
Hi Matt - what is the vision here? Is it possible to elaborate? I may be able to help here.

**Comment by rhyolight** [comment]
I'm basically looking for a simple HTTP client module users can install with npm and not worry about making requests themselves. Look at https://github.com/nupic-community/htmengine-traffic-tutorial/blob/master/node-client/lib/traffic-data-client.js for inspiration. 

I'm imagining a use-case like this:

```javascript
var RiverView = require('river-view-client');

var rv = new RiverView('rv-url');

rv.getRivers(function(err, rivers) {
  var river = rivers.shift();
  river.getStreams(function(err, streams) {
    var stream = streams.shift();
    stream.getData({since:<date>, until:<date>}, function(err, data) {});
    stream.getMetaData({since:<date>, until:<date>}, function(err, meta) {});
  });
});
```

**Comment by jefffohl** [comment]
Ah, ok cool. Sounds great. Do you want help with it?

**Comment by rhyolight** [comment]
Yes please!

**Comment by rhyolight** [comment]
Feel free to start this repo off on your own GitHub, but we'll probably move it later.

**Comment by jefffohl** [comment]
Cool. I want to make sure I capture all of the functionality needed. Should we write up a set of requirements or an API that it should fulfill?

**Comment by rhyolight** [comment]
How about you write up a spec, and I'll review?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
OK, sounds good.

**Comment by rhyolight** [comment]
The way I would do it is have `River` and `Stream` classes. You can look at
https://github.com/rhyolight/travis-foreman/blob/master/foreman.js and
https://github.com/rhyolight/sprinter.js/blob/master/sprinter.js for
 examples of the type of API clients I usually make.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
Great - thanks for the examples. I want it to go with the flow you expect.

**Comment by jefffohl** [comment]
Hey @rhyolight - sorry I haven't jumped on this yet. What is the timeframe in which you hope to get this accomplished?

**Comment by rhyolight** [comment]
Whenever.

**Comment by jefffohl** [comment]
You live dangerously, sir.

**Comment by rhyolight** [comment]
How about... By September 16th?

**Comment by jefffohl** [comment]
Sounds good. I will give it a shot!

**Comment by rhyolight** [comment]
see https://github.com/nupic-community/river-view/issues/88
